snc_redis:
  clients:
    default:
      type: phpredis
      alias: default
      dsn:
        - "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%"
      logging: "%kernel.debug%"
      options:
        prefix: rdg_
        connection_timeout: 10
        connection_persistent: true
        throw_errors: true
        cluster: "%env(REDIS_CLUSTER)%"
        parameters:
          username: "%env(REDIS_USERNAME)%"
          password: "%env(REDIS_PASSWORD)%"
