vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        s3file:
            upload_destination: ceph.storage
            directory_namer: 
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options: { property: 's3FileCategory' } 
