<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220324160644 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE actuality (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, is_published TINYINT(1) NOT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_4093DDD8DE12AB56 (created_by), INDEX IDX_4093DDD816FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE actualities_taxonomies (actuality_id INT NOT NULL, taxonomy_id INT NOT NULL, INDEX IDX_ED96E436B84BD854 (actuality_id), INDEX IDX_ED96E4369557E6F6 (taxonomy_id), PRIMARY KEY(actuality_id, taxonomy_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE actuality_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, slug VARCHAR(510) NOT NULL, locale VARCHAR(5) NOT NULL, UNIQUE INDEX UNIQ_80A121D2989D9B62 (slug), INDEX IDX_80A121D22C2AC5D3 (translatable_id), UNIQUE INDEX actuality_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE additional_help (id INT AUTO_INCREMENT NOT NULL, guide_id INT DEFAULT NULL, displayed TINYINT(1) NOT NULL, weight INT NOT NULL, link VARCHAR(510) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_2613DA62D7ED1D4B (guide_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE additional_help_guide (id INT AUTO_INCREMENT NOT NULL, guide_id INT NOT NULL, additional_help_id INT NOT NULL, weight INT NOT NULL, INDEX IDX_B8B32023D7ED1D4B (guide_id), INDEX IDX_B8B32023D27BB613 (additional_help_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE additional_help_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_FE3F74FB2C2AC5D3 (translatable_id), UNIQUE INDEX additional_help_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alert_msg (id INT AUTO_INCREMENT NOT NULL, updated_by INT DEFAULT NULL, type SMALLINT NOT NULL, date_start DATETIME DEFAULT NULL, date_end DATETIME DEFAULT NULL, INDEX IDX_BDC6247316FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alert_msg_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_43CF01EC2C2AC5D3 (translatable_id), UNIQUE INDEX alert_msg_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, weight INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_64C19C1DE12AB56 (created_by), INDEX IDX_64C19C116FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_guide (id INT AUTO_INCREMENT NOT NULL, guide_id INT NOT NULL, category_id INT NOT NULL, weight INT NOT NULL, INDEX IDX_22AD887CD7ED1D4B (guide_id), INDEX IDX_22AD887C12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(64) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_3F207042C2AC5D3 (translatable_id), UNIQUE INDEX category_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE config (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, data LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_subject (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, weight INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_61E11FFBDE12AB56 (created_by), INDEX IDX_61E11FFB16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_subject_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, subject VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_71FD7E2E2C2AC5D3 (translatable_id), UNIQUE INDEX contact_subject_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE data_workshop_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, acronym VARCHAR(255) NOT NULL, extended_name VARCHAR(510) NOT NULL, description LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_665572952C2AC5D3 (translatable_id), UNIQUE INDEX data_workshop_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dataset (id INT AUTO_INCREMENT NOT NULL, actuality_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, dataset_quote LONGTEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, persistent_id VARCHAR(255) DEFAULT NULL, link_dataverse VARCHAR(512) DEFAULT NULL, is_published TINYINT(1) NOT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_B7A041D0B84BD854 (actuality_id), INDEX IDX_B7A041D0DE12AB56 (created_by), INDEX IDX_B7A041D016FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE datasets_taxonomies (dataset_id INT NOT NULL, taxonomy_id INT NOT NULL, INDEX IDX_CDC10040D47C2D1B (dataset_id), INDEX IDX_CDC100409557E6F6 (taxonomy_id), PRIMARY KEY(dataset_id, taxonomy_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dataset_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, hook LONGTEXT NOT NULL, content LONGTEXT NOT NULL, slug VARCHAR(510) NOT NULL, locale VARCHAR(5) NOT NULL, UNIQUE INDEX UNIQ_24F3A3D7989D9B62 (slug), INDEX IDX_24F3A3D72C2AC5D3 (translatable_id), UNIQUE INDEX dataset_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dataworkshop (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, url_data_workshop VARCHAR(2048) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_8B2CB548DE12AB56 (created_by), INDEX IDX_8B2CB54816FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE institutions_dataworkshops (institution_id INT NOT NULL, dataworkshop_id INT NOT NULL, INDEX IDX_F93EEE3110405986 (institution_id), INDEX IDX_F93EEE31B3A22FDD (dataworkshop_id), PRIMARY KEY(institution_id, dataworkshop_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, begin DATETIME NOT NULL, end DATETIME DEFAULT NULL, link VARCHAR(255) NOT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3BAE0AA7DE12AB56 (created_by), INDEX IDX_3BAE0AA716FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_taxonomies (event_id INT NOT NULL, taxonomy_id INT NOT NULL, INDEX IDX_F6D2357871F7E88B (event_id), INDEX IDX_F6D235789557E6F6 (taxonomy_id), PRIMARY KEY(event_id, taxonomy_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, hook VARCHAR(150) NOT NULL, content LONGTEXT NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_1FE096EF2C2AC5D3 (translatable_id), UNIQUE INDEX event_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq_block (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, weight INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_27CF4D27DE12AB56 (created_by), INDEX IDX_27CF4D2716FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq_block_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_F4852B482C2AC5D3 (translatable_id), UNIQUE INDEX faq_block_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE glossary (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_B0850B43DE12AB56 (created_by), INDEX IDX_B0850B4316FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE glossary_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, term VARCHAR(255) NOT NULL, definition LONGTEXT NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_C640170D2C2AC5D3 (translatable_id), UNIQUE INDEX glossary_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE guide (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, is_published TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, published_at DATETIME DEFAULT NULL, INDEX IDX_CA9EC735DE12AB56 (created_by), INDEX IDX_CA9EC73516FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE guide_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT DEFAULT NULL, slug VARCHAR(510) NOT NULL, locale VARCHAR(5) NOT NULL, UNIQUE INDEX UNIQ_1C47BEFA989D9B62 (slug), INDEX IDX_1C47BEFA2C2AC5D3 (translatable_id), UNIQUE INDEX guide_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE heading (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, weight INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_2B43FC1DE12AB56 (created_by), INDEX IDX_2B43FC116FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE heading_faq (id INT AUTO_INCREMENT NOT NULL, faq_id INT NOT NULL, heading_id INT NOT NULL, weight INT NOT NULL, INDEX IDX_2AF54D6881BEC8C2 (faq_id), INDEX IDX_2AF54D6862FE64EC (heading_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE heading_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(64) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_33ACDFF12C2AC5D3 (translatable_id), UNIQUE INDEX heading_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE institution (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, url_institution VARCHAR(2048) DEFAULT NULL, url_collection VARCHAR(2048) DEFAULT NULL, url_collection_contact VARCHAR(2048) DEFAULT NULL, url_open_science VARCHAR(2048) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3A9F98E5DE12AB56 (created_by), INDEX IDX_3A9F98E516FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE institution_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, acronym VARCHAR(255) NOT NULL, extended_name VARCHAR(510) NOT NULL, description LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_D2890A502C2AC5D3 (translatable_id), UNIQUE INDEX institution_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE introduction (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, enable_background TINYINT(1) NOT NULL, route_type VARCHAR(250) NOT NULL, is_enable TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_F5005424DE12AB56 (created_by), INDEX IDX_F500542416FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE introduction_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(2048) DEFAULT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_E5E53F652C2AC5D3 (translatable_id), UNIQUE INDEX introduction_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_carousel (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, weight INT NOT NULL, is_published TINYINT(1) NOT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_515A0785DE12AB56 (created_by), INDEX IDX_515A078516FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_carousels_centers (carousel_lame_id INT NOT NULL, institution_id INT NOT NULL, INDEX IDX_7F702F29842758D1 (carousel_lame_id), INDEX IDX_7F702F2910405986 (institution_id), PRIMARY KEY(carousel_lame_id, institution_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_carousel_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_F094B9562C2AC5D3 (translatable_id), UNIQUE INDEX lame_carousel_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_center_map (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, weight INT NOT NULL, is_published TINYINT(1) NOT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_6697557DE12AB56 (created_by), INDEX IDX_669755716FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_center_map_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content VARCHAR(1000) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_73AAEC932C2AC5D3 (translatable_id), UNIQUE INDEX lame_center_map_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_highlighted (id INT AUTO_INCREMENT NOT NULL, dataset_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, weight INT NOT NULL, is_published TINYINT(1) NOT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_A420216AD47C2D1B (dataset_id), INDEX IDX_A420216ADE12AB56 (created_by), INDEX IDX_A420216A16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_highlighted_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_99B6F3DF2C2AC5D3 (translatable_id), UNIQUE INDEX lame_highlighted_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_news (id INT AUTO_INCREMENT NOT NULL, actu_first INT DEFAULT NULL, actu_second INT DEFAULT NULL, actu_third INT DEFAULT NULL, event_first INT DEFAULT NULL, event_second INT DEFAULT NULL, event_third INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, auto_actu TINYINT(1) NOT NULL, auto_event TINYINT(1) NOT NULL, weight INT NOT NULL, is_published TINYINT(1) NOT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_74936BA1878079D7 (actu_first), INDEX IDX_74936BA15BB263DE (actu_second), INDEX IDX_74936BA131C3B7E4 (actu_third), INDEX IDX_74936BA1D36A5F7B (event_first), INDEX IDX_74936BA18486663B (event_second), INDEX IDX_74936BA165299148 (event_third), INDEX IDX_74936BA1DE12AB56 (created_by), INDEX IDX_74936BA116FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_news_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_FDA1BFA92C2AC5D3 (translatable_id), UNIQUE INDEX lame_news_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_spotlight (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, weight INT NOT NULL, is_published TINYINT(1) NOT NULL, published_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_5E9C58F0DE12AB56 (created_by), INDEX IDX_5E9C58F016FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_spotlights_datasets (spot_light_lame_id INT NOT NULL, dataset_id INT NOT NULL, INDEX IDX_7954E61EAA95B13C (spot_light_lame_id), INDEX IDX_7954E61ED47C2D1B (dataset_id), PRIMARY KEY(spot_light_lame_id, dataset_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lame_spotlight_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_D23D7672C2AC5D3 (translatable_id), UNIQUE INDEX lame_spotlight_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE menu_basic (id INT AUTO_INCREMENT NOT NULL, page_link INT DEFAULT NULL, external_link VARCHAR(510) DEFAULT NULL, system_link VARCHAR(255) DEFAULT NULL, weight INT NOT NULL, is_activated TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_1D55634B168852B (page_link), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE menu_basic_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_C3B3BDC32C2AC5D3 (translatable_id), UNIQUE INDEX menu_basic_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE menu_multiple (id INT AUTO_INCREMENT NOT NULL, page_link INT DEFAULT NULL, parent_id INT DEFAULT NULL, external_link VARCHAR(510) DEFAULT NULL, system_link VARCHAR(255) DEFAULT NULL, weight INT NOT NULL, is_activated TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_29E63892B168852B (page_link), INDEX IDX_29E63892727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE menu_multiple_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_EC3708852C2AC5D3 (translatable_id), UNIQUE INDEX menu_multiple_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, is_published TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, published_at DATETIME DEFAULT NULL, INDEX IDX_140AB620DE12AB56 (created_by), INDEX IDX_140AB62016FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, slug VARCHAR(510) NOT NULL, locale VARCHAR(5) NOT NULL, UNIQUE INDEX UNIQ_A3D51B1D989D9B62 (slug), INDEX IDX_A3D51B1D2C2AC5D3 (translatable_id), UNIQUE INDEX page_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE social_network (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, name VARCHAR(255) NOT NULL, link VARCHAR(510) NOT NULL, image VARCHAR(255) NOT NULL, weight INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_EFFF5221DE12AB56 (created_by), INDEX IDX_EFFF522116FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE taxonomy (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE taxonomy_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, term VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, INDEX IDX_C1F82AA52C2AC5D3 (translatable_id), UNIQUE INDEX taxonomy_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, is_activated TINYINT(1) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE actuality ADD CONSTRAINT FK_4093DDD8DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE actuality ADD CONSTRAINT FK_4093DDD816FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE actualities_taxonomies ADD CONSTRAINT FK_ED96E436B84BD854 FOREIGN KEY (actuality_id) REFERENCES actuality (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE actualities_taxonomies ADD CONSTRAINT FK_ED96E4369557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomy (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE actuality_translation ADD CONSTRAINT FK_80A121D22C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES actuality (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE additional_help ADD CONSTRAINT FK_2613DA62D7ED1D4B FOREIGN KEY (guide_id) REFERENCES guide (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE additional_help_guide ADD CONSTRAINT FK_B8B32023D7ED1D4B FOREIGN KEY (guide_id) REFERENCES guide (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE additional_help_guide ADD CONSTRAINT FK_B8B32023D27BB613 FOREIGN KEY (additional_help_id) REFERENCES additional_help (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE additional_help_translation ADD CONSTRAINT FK_FE3F74FB2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES additional_help (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alert_msg ADD CONSTRAINT FK_BDC6247316FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE alert_msg_translation ADD CONSTRAINT FK_43CF01EC2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES alert_msg (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE category_guide ADD CONSTRAINT FK_22AD887CD7ED1D4B FOREIGN KEY (guide_id) REFERENCES guide (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_guide ADD CONSTRAINT FK_22AD887C12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_translation ADD CONSTRAINT FK_3F207042C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_subject ADD CONSTRAINT FK_61E11FFBDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contact_subject ADD CONSTRAINT FK_61E11FFB16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contact_subject_translation ADD CONSTRAINT FK_71FD7E2E2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES contact_subject (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE data_workshop_translation ADD CONSTRAINT FK_665572952C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES dataworkshop (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D0B84BD854 FOREIGN KEY (actuality_id) REFERENCES actuality (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D0DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE dataset ADD CONSTRAINT FK_B7A041D016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE datasets_taxonomies ADD CONSTRAINT FK_CDC10040D47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE datasets_taxonomies ADD CONSTRAINT FK_CDC100409557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomy (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dataset_translation ADD CONSTRAINT FK_24F3A3D72C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES dataset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dataworkshop ADD CONSTRAINT FK_8B2CB548DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE dataworkshop ADD CONSTRAINT FK_8B2CB54816FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE institutions_dataworkshops ADD CONSTRAINT FK_F93EEE3110405986 FOREIGN KEY (institution_id) REFERENCES dataworkshop (id)');
        $this->addSql('ALTER TABLE institutions_dataworkshops ADD CONSTRAINT FK_F93EEE31B3A22FDD FOREIGN KEY (dataworkshop_id) REFERENCES institution (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA716FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE events_taxonomies ADD CONSTRAINT FK_F6D2357871F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_taxonomies ADD CONSTRAINT FK_F6D235789557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomy (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_translation ADD CONSTRAINT FK_1FE096EF2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE faq_block ADD CONSTRAINT FK_27CF4D27DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE faq_block ADD CONSTRAINT FK_27CF4D2716FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE faq_block_translation ADD CONSTRAINT FK_F4852B482C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES faq_block (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE glossary ADD CONSTRAINT FK_B0850B43DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE glossary ADD CONSTRAINT FK_B0850B4316FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE glossary_translation ADD CONSTRAINT FK_C640170D2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES glossary (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE guide ADD CONSTRAINT FK_CA9EC735DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE guide ADD CONSTRAINT FK_CA9EC73516FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE guide_translation ADD CONSTRAINT FK_1C47BEFA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES guide (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE heading ADD CONSTRAINT FK_2B43FC1DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE heading ADD CONSTRAINT FK_2B43FC116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE heading_faq ADD CONSTRAINT FK_2AF54D6881BEC8C2 FOREIGN KEY (faq_id) REFERENCES faq_block (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE heading_faq ADD CONSTRAINT FK_2AF54D6862FE64EC FOREIGN KEY (heading_id) REFERENCES heading (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE heading_translation ADD CONSTRAINT FK_33ACDFF12C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES heading (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE institution ADD CONSTRAINT FK_3A9F98E5DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE institution ADD CONSTRAINT FK_3A9F98E516FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE institution_translation ADD CONSTRAINT FK_D2890A502C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES institution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE introduction ADD CONSTRAINT FK_F5005424DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE introduction ADD CONSTRAINT FK_F500542416FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE introduction_translation ADD CONSTRAINT FK_E5E53F652C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES introduction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_carousel ADD CONSTRAINT FK_515A0785DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_carousel ADD CONSTRAINT FK_515A078516FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_carousels_centers ADD CONSTRAINT FK_7F702F29842758D1 FOREIGN KEY (carousel_lame_id) REFERENCES lame_carousel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_carousels_centers ADD CONSTRAINT FK_7F702F2910405986 FOREIGN KEY (institution_id) REFERENCES institution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_carousel_translation ADD CONSTRAINT FK_F094B9562C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES lame_carousel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_center_map ADD CONSTRAINT FK_6697557DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_center_map ADD CONSTRAINT FK_669755716FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_center_map_translation ADD CONSTRAINT FK_73AAEC932C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES lame_center_map (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_highlighted ADD CONSTRAINT FK_A420216AD47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_highlighted ADD CONSTRAINT FK_A420216ADE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_highlighted ADD CONSTRAINT FK_A420216A16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_highlighted_translation ADD CONSTRAINT FK_99B6F3DF2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES lame_highlighted (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_news ADD CONSTRAINT FK_74936BA1878079D7 FOREIGN KEY (actu_first) REFERENCES actuality (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_news ADD CONSTRAINT FK_74936BA15BB263DE FOREIGN KEY (actu_second) REFERENCES actuality (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_news ADD CONSTRAINT FK_74936BA131C3B7E4 FOREIGN KEY (actu_third) REFERENCES actuality (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_news ADD CONSTRAINT FK_74936BA1D36A5F7B FOREIGN KEY (event_first) REFERENCES event (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_news ADD CONSTRAINT FK_74936BA18486663B FOREIGN KEY (event_second) REFERENCES event (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_news ADD CONSTRAINT FK_74936BA165299148 FOREIGN KEY (event_third) REFERENCES event (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_news ADD CONSTRAINT FK_74936BA1DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_news ADD CONSTRAINT FK_74936BA116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_news_translation ADD CONSTRAINT FK_FDA1BFA92C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES lame_news (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_spotlight ADD CONSTRAINT FK_5E9C58F0DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_spotlight ADD CONSTRAINT FK_5E9C58F016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lame_spotlights_datasets ADD CONSTRAINT FK_7954E61EAA95B13C FOREIGN KEY (spot_light_lame_id) REFERENCES lame_spotlight (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_spotlights_datasets ADD CONSTRAINT FK_7954E61ED47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lame_spotlight_translation ADD CONSTRAINT FK_D23D7672C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES lame_spotlight (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_basic ADD CONSTRAINT FK_1D55634B168852B FOREIGN KEY (page_link) REFERENCES page (id)');
        $this->addSql('ALTER TABLE menu_basic_translation ADD CONSTRAINT FK_C3B3BDC32C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES menu_basic (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_multiple ADD CONSTRAINT FK_29E63892B168852B FOREIGN KEY (page_link) REFERENCES page (id)');
        $this->addSql('ALTER TABLE menu_multiple ADD CONSTRAINT FK_29E63892727ACA70 FOREIGN KEY (parent_id) REFERENCES menu_multiple (id)');
        $this->addSql('ALTER TABLE menu_multiple_translation ADD CONSTRAINT FK_EC3708852C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES menu_multiple (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB62016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE page_translation ADD CONSTRAINT FK_A3D51B1D2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE social_network ADD CONSTRAINT FK_EFFF5221DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE social_network ADD CONSTRAINT FK_EFFF522116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE taxonomy_translation ADD CONSTRAINT FK_C1F82AA52C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES taxonomy (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE actualities_taxonomies DROP FOREIGN KEY FK_ED96E436B84BD854');
        $this->addSql('ALTER TABLE actuality_translation DROP FOREIGN KEY FK_80A121D22C2AC5D3');
        $this->addSql('ALTER TABLE dataset DROP FOREIGN KEY FK_B7A041D0B84BD854');
        $this->addSql('ALTER TABLE lame_news DROP FOREIGN KEY FK_74936BA1878079D7');
        $this->addSql('ALTER TABLE lame_news DROP FOREIGN KEY FK_74936BA15BB263DE');
        $this->addSql('ALTER TABLE lame_news DROP FOREIGN KEY FK_74936BA131C3B7E4');
        $this->addSql('ALTER TABLE additional_help_guide DROP FOREIGN KEY FK_B8B32023D27BB613');
        $this->addSql('ALTER TABLE additional_help_translation DROP FOREIGN KEY FK_FE3F74FB2C2AC5D3');
        $this->addSql('ALTER TABLE alert_msg_translation DROP FOREIGN KEY FK_43CF01EC2C2AC5D3');
        $this->addSql('ALTER TABLE category_guide DROP FOREIGN KEY FK_22AD887C12469DE2');
        $this->addSql('ALTER TABLE category_translation DROP FOREIGN KEY FK_3F207042C2AC5D3');
        $this->addSql('ALTER TABLE contact_subject_translation DROP FOREIGN KEY FK_71FD7E2E2C2AC5D3');
        $this->addSql('ALTER TABLE datasets_taxonomies DROP FOREIGN KEY FK_CDC10040D47C2D1B');
        $this->addSql('ALTER TABLE dataset_translation DROP FOREIGN KEY FK_24F3A3D72C2AC5D3');
        $this->addSql('ALTER TABLE lame_highlighted DROP FOREIGN KEY FK_A420216AD47C2D1B');
        $this->addSql('ALTER TABLE lame_spotlights_datasets DROP FOREIGN KEY FK_7954E61ED47C2D1B');
        $this->addSql('ALTER TABLE data_workshop_translation DROP FOREIGN KEY FK_665572952C2AC5D3');
        $this->addSql('ALTER TABLE institutions_dataworkshops DROP FOREIGN KEY FK_F93EEE3110405986');
        $this->addSql('ALTER TABLE events_taxonomies DROP FOREIGN KEY FK_F6D2357871F7E88B');
        $this->addSql('ALTER TABLE event_translation DROP FOREIGN KEY FK_1FE096EF2C2AC5D3');
        $this->addSql('ALTER TABLE lame_news DROP FOREIGN KEY FK_74936BA1D36A5F7B');
        $this->addSql('ALTER TABLE lame_news DROP FOREIGN KEY FK_74936BA18486663B');
        $this->addSql('ALTER TABLE lame_news DROP FOREIGN KEY FK_74936BA165299148');
        $this->addSql('ALTER TABLE faq_block_translation DROP FOREIGN KEY FK_F4852B482C2AC5D3');
        $this->addSql('ALTER TABLE heading_faq DROP FOREIGN KEY FK_2AF54D6881BEC8C2');
        $this->addSql('ALTER TABLE glossary_translation DROP FOREIGN KEY FK_C640170D2C2AC5D3');
        $this->addSql('ALTER TABLE additional_help DROP FOREIGN KEY FK_2613DA62D7ED1D4B');
        $this->addSql('ALTER TABLE additional_help_guide DROP FOREIGN KEY FK_B8B32023D7ED1D4B');
        $this->addSql('ALTER TABLE category_guide DROP FOREIGN KEY FK_22AD887CD7ED1D4B');
        $this->addSql('ALTER TABLE guide_translation DROP FOREIGN KEY FK_1C47BEFA2C2AC5D3');
        $this->addSql('ALTER TABLE heading_faq DROP FOREIGN KEY FK_2AF54D6862FE64EC');
        $this->addSql('ALTER TABLE heading_translation DROP FOREIGN KEY FK_33ACDFF12C2AC5D3');
        $this->addSql('ALTER TABLE institutions_dataworkshops DROP FOREIGN KEY FK_F93EEE31B3A22FDD');
        $this->addSql('ALTER TABLE institution_translation DROP FOREIGN KEY FK_D2890A502C2AC5D3');
        $this->addSql('ALTER TABLE lame_carousels_centers DROP FOREIGN KEY FK_7F702F2910405986');
        $this->addSql('ALTER TABLE introduction_translation DROP FOREIGN KEY FK_E5E53F652C2AC5D3');
        $this->addSql('ALTER TABLE lame_carousels_centers DROP FOREIGN KEY FK_7F702F29842758D1');
        $this->addSql('ALTER TABLE lame_carousel_translation DROP FOREIGN KEY FK_F094B9562C2AC5D3');
        $this->addSql('ALTER TABLE lame_center_map_translation DROP FOREIGN KEY FK_73AAEC932C2AC5D3');
        $this->addSql('ALTER TABLE lame_highlighted_translation DROP FOREIGN KEY FK_99B6F3DF2C2AC5D3');
        $this->addSql('ALTER TABLE lame_news_translation DROP FOREIGN KEY FK_FDA1BFA92C2AC5D3');
        $this->addSql('ALTER TABLE lame_spotlights_datasets DROP FOREIGN KEY FK_7954E61EAA95B13C');
        $this->addSql('ALTER TABLE lame_spotlight_translation DROP FOREIGN KEY FK_D23D7672C2AC5D3');
        $this->addSql('ALTER TABLE menu_basic_translation DROP FOREIGN KEY FK_C3B3BDC32C2AC5D3');
        $this->addSql('ALTER TABLE menu_multiple DROP FOREIGN KEY FK_29E63892727ACA70');
        $this->addSql('ALTER TABLE menu_multiple_translation DROP FOREIGN KEY FK_EC3708852C2AC5D3');
        $this->addSql('ALTER TABLE menu_basic DROP FOREIGN KEY FK_1D55634B168852B');
        $this->addSql('ALTER TABLE menu_multiple DROP FOREIGN KEY FK_29E63892B168852B');
        $this->addSql('ALTER TABLE page_translation DROP FOREIGN KEY FK_A3D51B1D2C2AC5D3');
        $this->addSql('ALTER TABLE actualities_taxonomies DROP FOREIGN KEY FK_ED96E4369557E6F6');
        $this->addSql('ALTER TABLE datasets_taxonomies DROP FOREIGN KEY FK_CDC100409557E6F6');
        $this->addSql('ALTER TABLE events_taxonomies DROP FOREIGN KEY FK_F6D235789557E6F6');
        $this->addSql('ALTER TABLE taxonomy_translation DROP FOREIGN KEY FK_C1F82AA52C2AC5D3');
        $this->addSql('ALTER TABLE actuality DROP FOREIGN KEY FK_4093DDD8DE12AB56');
        $this->addSql('ALTER TABLE actuality DROP FOREIGN KEY FK_4093DDD816FE72E1');
        $this->addSql('ALTER TABLE alert_msg DROP FOREIGN KEY FK_BDC6247316FE72E1');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1DE12AB56');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C116FE72E1');
        $this->addSql('ALTER TABLE contact_subject DROP FOREIGN KEY FK_61E11FFBDE12AB56');
        $this->addSql('ALTER TABLE contact_subject DROP FOREIGN KEY FK_61E11FFB16FE72E1');
        $this->addSql('ALTER TABLE dataset DROP FOREIGN KEY FK_B7A041D0DE12AB56');
        $this->addSql('ALTER TABLE dataset DROP FOREIGN KEY FK_B7A041D016FE72E1');
        $this->addSql('ALTER TABLE dataworkshop DROP FOREIGN KEY FK_8B2CB548DE12AB56');
        $this->addSql('ALTER TABLE dataworkshop DROP FOREIGN KEY FK_8B2CB54816FE72E1');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7DE12AB56');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA716FE72E1');
        $this->addSql('ALTER TABLE faq_block DROP FOREIGN KEY FK_27CF4D27DE12AB56');
        $this->addSql('ALTER TABLE faq_block DROP FOREIGN KEY FK_27CF4D2716FE72E1');
        $this->addSql('ALTER TABLE glossary DROP FOREIGN KEY FK_B0850B43DE12AB56');
        $this->addSql('ALTER TABLE glossary DROP FOREIGN KEY FK_B0850B4316FE72E1');
        $this->addSql('ALTER TABLE guide DROP FOREIGN KEY FK_CA9EC735DE12AB56');
        $this->addSql('ALTER TABLE guide DROP FOREIGN KEY FK_CA9EC73516FE72E1');
        $this->addSql('ALTER TABLE heading DROP FOREIGN KEY FK_2B43FC1DE12AB56');
        $this->addSql('ALTER TABLE heading DROP FOREIGN KEY FK_2B43FC116FE72E1');
        $this->addSql('ALTER TABLE institution DROP FOREIGN KEY FK_3A9F98E5DE12AB56');
        $this->addSql('ALTER TABLE institution DROP FOREIGN KEY FK_3A9F98E516FE72E1');
        $this->addSql('ALTER TABLE introduction DROP FOREIGN KEY FK_F5005424DE12AB56');
        $this->addSql('ALTER TABLE introduction DROP FOREIGN KEY FK_F500542416FE72E1');
        $this->addSql('ALTER TABLE lame_carousel DROP FOREIGN KEY FK_515A0785DE12AB56');
        $this->addSql('ALTER TABLE lame_carousel DROP FOREIGN KEY FK_515A078516FE72E1');
        $this->addSql('ALTER TABLE lame_center_map DROP FOREIGN KEY FK_6697557DE12AB56');
        $this->addSql('ALTER TABLE lame_center_map DROP FOREIGN KEY FK_669755716FE72E1');
        $this->addSql('ALTER TABLE lame_highlighted DROP FOREIGN KEY FK_A420216ADE12AB56');
        $this->addSql('ALTER TABLE lame_highlighted DROP FOREIGN KEY FK_A420216A16FE72E1');
        $this->addSql('ALTER TABLE lame_news DROP FOREIGN KEY FK_74936BA1DE12AB56');
        $this->addSql('ALTER TABLE lame_news DROP FOREIGN KEY FK_74936BA116FE72E1');
        $this->addSql('ALTER TABLE lame_spotlight DROP FOREIGN KEY FK_5E9C58F0DE12AB56');
        $this->addSql('ALTER TABLE lame_spotlight DROP FOREIGN KEY FK_5E9C58F016FE72E1');
        $this->addSql('ALTER TABLE page DROP FOREIGN KEY FK_140AB620DE12AB56');
        $this->addSql('ALTER TABLE page DROP FOREIGN KEY FK_140AB62016FE72E1');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE social_network DROP FOREIGN KEY FK_EFFF5221DE12AB56');
        $this->addSql('ALTER TABLE social_network DROP FOREIGN KEY FK_EFFF522116FE72E1');
        $this->addSql('DROP TABLE actuality');
        $this->addSql('DROP TABLE actualities_taxonomies');
        $this->addSql('DROP TABLE actuality_translation');
        $this->addSql('DROP TABLE additional_help');
        $this->addSql('DROP TABLE additional_help_guide');
        $this->addSql('DROP TABLE additional_help_translation');
        $this->addSql('DROP TABLE alert_msg');
        $this->addSql('DROP TABLE alert_msg_translation');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE category_guide');
        $this->addSql('DROP TABLE category_translation');
        $this->addSql('DROP TABLE config');
        $this->addSql('DROP TABLE contact_subject');
        $this->addSql('DROP TABLE contact_subject_translation');
        $this->addSql('DROP TABLE data_workshop_translation');
        $this->addSql('DROP TABLE dataset');
        $this->addSql('DROP TABLE datasets_taxonomies');
        $this->addSql('DROP TABLE dataset_translation');
        $this->addSql('DROP TABLE dataworkshop');
        $this->addSql('DROP TABLE institutions_dataworkshops');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE events_taxonomies');
        $this->addSql('DROP TABLE event_translation');
        $this->addSql('DROP TABLE faq_block');
        $this->addSql('DROP TABLE faq_block_translation');
        $this->addSql('DROP TABLE glossary');
        $this->addSql('DROP TABLE glossary_translation');
        $this->addSql('DROP TABLE guide');
        $this->addSql('DROP TABLE guide_translation');
        $this->addSql('DROP TABLE heading');
        $this->addSql('DROP TABLE heading_faq');
        $this->addSql('DROP TABLE heading_translation');
        $this->addSql('DROP TABLE institution');
        $this->addSql('DROP TABLE institution_translation');
        $this->addSql('DROP TABLE introduction');
        $this->addSql('DROP TABLE introduction_translation');
        $this->addSql('DROP TABLE lame_carousel');
        $this->addSql('DROP TABLE lame_carousels_centers');
        $this->addSql('DROP TABLE lame_carousel_translation');
        $this->addSql('DROP TABLE lame_center_map');
        $this->addSql('DROP TABLE lame_center_map_translation');
        $this->addSql('DROP TABLE lame_highlighted');
        $this->addSql('DROP TABLE lame_highlighted_translation');
        $this->addSql('DROP TABLE lame_news');
        $this->addSql('DROP TABLE lame_news_translation');
        $this->addSql('DROP TABLE lame_spotlight');
        $this->addSql('DROP TABLE lame_spotlights_datasets');
        $this->addSql('DROP TABLE lame_spotlight_translation');
        $this->addSql('DROP TABLE menu_basic');
        $this->addSql('DROP TABLE menu_basic_translation');
        $this->addSql('DROP TABLE menu_multiple');
        $this->addSql('DROP TABLE menu_multiple_translation');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE page_translation');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE social_network');
        $this->addSql('DROP TABLE taxonomy');
        $this->addSql('DROP TABLE taxonomy_translation');
        $this->addSql('DROP TABLE user');
    }
}
